// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Preferences } from '@capacitor/preferences';
import { Capacitor } from '@capacitor/core';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Missing Supabase environment variables. Please check your .env file.");
  throw new Error("Missing Supabase environment variables. Please check your .env file.");
}

// Custom storage adapter for Capacitor Preferences
const capacitorStorage = {
  getItem: async (key: string): Promise<string | null> => {
    try {
      if (typeof localStorage !== 'undefined') {
        return localStorage.getItem(key);
      }
    } catch (error) {
      console.warn('localStorage.getItem failed:', error);
    }

    try {
      if (!Capacitor.isNativePlatform()) {
        return null;
      }
    } catch {
      return null;
    }

    try {
      // Add timeout to prevent hanging
      const timeoutPromise = new Promise<null>((_, reject) => 
        setTimeout(() => reject(new Error("Preferences.get timeout")), 2000)
      );
      const getPromise = Preferences.get({ key });
      const result = await Promise.race([getPromise, timeoutPromise]) as { value: string | null };
      return result.value;
    } catch (error) {
      console.warn('Preferences.get failed or timed out:', error);
      return null;
    }
  },
  setItem: async (key: string, value: string): Promise<void> => {
    try {
      if (typeof localStorage !== 'undefined') {
        localStorage.setItem(key, value);
        return;
      }
    } catch (error) {
      console.warn('localStorage.setItem failed:', error);
    }

    try {
      if (!Capacitor.isNativePlatform()) return;
    } catch {
      return;
    }

    try {
      const timeoutPromise = new Promise<void>((_, reject) => 
        setTimeout(() => reject(new Error("Preferences.set timeout")), 2000)
      );
      const setPromise = Preferences.set({ key, value });
      await Promise.race([setPromise, timeoutPromise]);
    } catch (error) {
      console.warn('Preferences.set failed or timed out:', error);
    }
  },
  removeItem: async (key: string): Promise<void> => {
    try {
      if (typeof localStorage !== 'undefined') {
        localStorage.removeItem(key);
        return;
      }
    } catch (error) {
      console.warn('localStorage.removeItem failed:', error);
    }

    try {
      if (!Capacitor.isNativePlatform()) return;
    } catch {
      return;
    }

    try {
      const timeoutPromise = new Promise<void>((_, reject) => 
        setTimeout(() => reject(new Error("Preferences.remove timeout")), 2000)
      );
      const removePromise = Preferences.remove({ key });
      await Promise.race([removePromise, timeoutPromise]);
    } catch (error) {
      console.warn('Preferences.remove failed or timed out:', error);
    }
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const createSupabaseClient = () => {
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: capacitorStorage,
      storageKey: `sb-elder-care-auth-token-${Math.random().toString(36).substring(7)}`, // Random key to completely bypass stuck locks
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
    },
  });
};

// Cache the client to avoid multiple instances during HMR
// which causes NavigatorLockAcquireTimeoutError
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const supabase = (globalThis as any).__supabaseClient || createSupabaseClient();

if (import.meta.env.DEV) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (globalThis as any).__supabaseClient = supabase;
}
